dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
jobs:
  allow_failures:
    # Sometimes nightly builds are broken, or contain breaking changes that affect dependencies we have
    # no control over. Thus we don't want a failed nightly run to cause Travis to consider the build broken.
    - python: 'nightly'
    - python: '3.9-dev'
install:
  - pip install pytest pytest-asyncio
  - pip install .
script: pytest -v -rxXs --log-cli-level=INFO tests/
